drpc:
  servers:
  - localhost
global:
  storageClass: tanzu
persistence:
  enabled: true
  storageClass: tanzu
security:
  groupid: 1000
  userid: 1000
supervisor:
  resources:
    limits: {}
    requests:
      cpu: 250m
      memory: 512
  worker:
    heap_memory_mb: 128
zookeeper:
  enabled: true
  readinessProbe:
    enabled: false
  replicaCount: 3
  securityContext:
    enabled: true
    fsGroup: 1000
    runAsUser: 1000
